# NB Seup

In [1]:
import numpy as np

# Basics

## Arrays

In [2]:
a = np.arange(2, 10, 2) # start = 2, end = 10, step = 2
a, type(a), type(a[0])

(array([2, 4, 6, 8]), numpy.ndarray, numpy.int64)

In [3]:
# generate array from list
from_list = np.array([1,2,3])
from_list

array([1, 2, 3])

In [4]:
# assign data type on instantiation
a = np.array([1,2,3], dtype=np.int8)
a, type(a[0])

(array([1, 2, 3], dtype=int8), numpy.int8)

In [5]:
# 2D arrays
a = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [6]:
# 2D array using np.arange
a = np.array((np.arange(0,8,2), np.arange(1,8,2)), dtype=np.int8)
a

array([[0, 2, 4, 6],
       [1, 3, 5, 7]], dtype=int8)

In [7]:
# shapes 1D
a = np.array(np.arange(10), dtype=np.int8)
a, a.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8), (10,))

In [8]:
# shapes nD
a = np.array((np.arange(0, 10, 2), np.arange(0, 10, 2), np.arange(0, 10, 2)), dtype=np.int8)
a, a.shape

(array([[0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8]], dtype=int8),
 (3, 5))

In [9]:
a = a.reshape(1,15)
a, a.shape

(array([[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8]], dtype=int8), (1, 15))

In [10]:
a = a.reshape(5, 3)
a, a.shape

(array([[0, 2, 4],
        [6, 8, 0],
        [2, 4, 6],
        [8, 0, 2],
        [4, 6, 8]], dtype=int8),
 (5, 3))

In [11]:
# empty arrays
e = np.zeros((2,2))
e

array([[0., 0.],
       [0., 0.]])

In [12]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [13]:
# return random values (it returns unexpected results. use np.zeros instead)
a = np.empty((2,2))
b = np.empty((2,2,2))

a, b

(array([[1., 1.],
        [1., 1.]]),
 array([[[2.171316e-316, 0.000000e+000],
         [0.000000e+000, 0.000000e+000]],
 
        [[0.000000e+000, 0.000000e+000],
         [0.000000e+000, 0.000000e+000]]]))

In [14]:
# filled with 0, while main diagonal is filled with 1
a = np.eye(3)

# filled with 0, and fill 1 based on k parameter
b = np.eye(3, k=1)
c = np.eye(5, k=-2)

a,b,c

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]]))

In [15]:
a = np.eye(3)
a1 = a.copy()
a1[a1==0] = 2 # change all 0 values of the array to 2

b = a.copy()
b[b < 1] = 9

c = a.copy()
c[0] = 3 # change the first row of the array to 3
c[1] = 4 # change the second row of the array to 4

d = a.copy()
d[:, 0] = 5 # change the first column of the array to 5
d[:, -1] = 6 # change the last row of the array to 6

e = np.eye(5)
e[1:, :2] = -5 # change from the first row till the last row, and for the first 2 columns

a,b,c,d,e

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 9., 9.],
        [9., 1., 9.],
        [9., 9., 1.]]),
 array([[3., 3., 3.],
        [4., 4., 4.],
        [0., 0., 1.]]),
 array([[5., 0., 6.],
        [5., 1., 6.],
        [5., 0., 6.]]),
 array([[ 1.,  0.,  0.,  0.,  0.],
        [-5., -5.,  0.,  0.,  0.],
        [-5., -5.,  1.,  0.,  0.],
        [-5., -5.,  0.,  1.,  0.],
        [-5., -5.,  0.,  0.,  1.]]))

In [16]:
# sort arrays

a = np.eye(3)

a[1:, :2] = 4
a[0, 0] = 2
a[0, 1] = 9
a[0, -1] = 2
a[1:, -1] = 3

col_sort = np.sort(a, axis=0, kind='quicksort') # sort based on columns. quicksort is the default algo
row_sort = np.sort(a, axis=1, kind='quicksort') # sort based on rows, which is default (1). quicksort is the default algo
a, col_sort, row_sort


(array([[2., 9., 2.],
        [4., 4., 3.],
        [4., 4., 3.]]),
 array([[2., 4., 2.],
        [4., 4., 3.],
        [4., 9., 3.]]),
 array([[2., 2., 9.],
        [3., 4., 4.],
        [3., 4., 4.]]))

In [17]:
# copy arrays
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
my_view = a.view() # acts as python shallow copy()
my_copy = a.copy() # acts as python deepcopy()

# view() creates a new array object that shares the same data as a.
#   Modifying my_view will affect a, and vice versa (as long as the modifications are done at the element level).
#   However, if you change the structure (like reshaping my_view), it does not affect a.

# copy() creates a new independent array with the same values as a.
#   Modifying my_copy will NOT affect a, and vice versa.
#   This is equivalent to Python's deepcopy() in that it creates a fully independent copy.

my_view, my_copy

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

## Operations

### Fill an array

In [18]:
# fill an array
a = np.zeros((3,3), dtype=np.int64)
b = a.copy()

a[:] = 2  # Uses broadcasting
b.fill(8) # Uses optimized in-place filling (more faster than [:], because it does not create an intermediate object—it simply updates memory locations )
a, b

(array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]),
 array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]))

In [19]:
a = np.zeros((3,3), dtype=np.int64)
a.fill(8)
b = a.copy()

a -= 2 # using broadcasting
b += [1,2,3] # using broadcasting

a,b

(array([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]),
 array([[ 9, 10, 11],
        [ 9, 10, 11],
        [ 9, 10, 11]]))

In [20]:
a = np.zeros((3,3), dtype=np.float64)
a.fill(8)
b,c = a.copy(), a.copy()

b /= 3 # using broadcasting to divide all by 3
c /= [1, 2, 3] # using broadcasting to divide every row based on index

a,b,c

(array([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]]),
 array([[2.66666667, 2.66666667, 2.66666667],
        [2.66666667, 2.66666667, 2.66666667],
        [2.66666667, 2.66666667, 2.66666667]]),
 array([[8.        , 4.        , 2.66666667],
        [8.        , 4.        , 2.66666667],
        [8.        , 4.        , 2.66666667]]))

### Sum

In [21]:
# sum of arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]])

sum_all_vals = a.sum()      # sum of all elements
sum_col_wise = a.sum(axis=0)     # sum all elements from each column of the same row (col-wise)
sum_row_wise = a.sum(axis=1)    # sum all elements from each row of the same column (row-wise)

a, sum_all_vals, sum_col_wise, sum_row_wise


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 45,
 array([12, 15, 18]),
 array([ 6, 15, 24]))

### Product

In [22]:
# prod of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

prod_all_vals = a.prod()
prod_col_wise = a.prod(axis=0)
prod_row_wise = a.prod(axis=1)

a, prod_all_vals, prod_col_wise, prod_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 362880,
 array([ 28,  80, 162]),
 array([  6, 120, 504]))

### Mean

In [23]:
# mean (average) of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

mean_all_vals = a.mean()
mean_col_wise = a.mean(axis=0)
mean_row_wise = a.mean(axis=1)

a, mean_all_vals, mean_col_wise, mean_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 5.0,
 array([4., 5., 6.]),
 array([2., 5., 8.]))

### Min - Max

In [24]:
# min max of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

min_val = a.min()
max_val = a.max()
min_col_wise = a.min(0)
min_row_wise = a.min(1)

a, min_val, max_val, min_col_wise, min_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 1,
 9,
 array([1, 2, 3]),
 array([1, 4, 7]))

In [25]:
# min max index of arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int64)

min_index = a.argmin()
max_index = a.argmax()

a, min_index, max_index

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 0,
 8)

### Peak to Peak

In [26]:
# peak-to-peak method

a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int64)
ptp = np.ptp(a)  # this equals to a.max() - a.min()
ptp

8

### Flatten

In [27]:
# flatten an array

a = np.array([[[0,1,2],[3,4,5], [6,7,8]], [[9,10,11],[12,13,14], [15,16,17]]])

# using reshape:
#   returns a new array with the same data but reshaped into a 1D array
#   may return a view or a copy, depending on the memory layout
#   less explicit than .ravel() or .flatten()
flatten_1 = a.reshape(a.size)
flatten_2 = a.reshape(-1)

# using flatten():
#   always returns a copy of the original array
#   changes to the new array do not affect the original array
#   takes an optional order argument ('C' for row-major, 'F' for column-major)
flat_method = a.flatten()

# using ravel():
#   returns a view of the array whenever possible (i.e., if the array is contiguous in memory)
#   if a view is returned, changes to ravel_method will affect the original array
#   if a copy is needed (e.g., if the array is not contiguous), it returns a new array
ravel_method = a.ravel()


a, flatten_1, flatten_2, flat_method, ravel_method

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]))

### Repeat

In [28]:
# repeat values/arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.repeat(255, 3) # first arg represents the value, the second arg represents the number of repetitions
repeat_arr_flat = np.repeat(a, 3)
repeat_arr_cols = np.repeat(a, 3, axis=0) # repeat col wise
repeat_arr_rows = np.repeat(a, 3, axis=1) # repeat row wise

a, b, repeat_arr_flat, repeat_arr_cols, repeat_arr_rows

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([255, 255, 255]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
        8, 8, 9, 9, 9]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]]),
 array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
        [4, 4, 4, 5, 5, 5, 6, 6, 6],
        [7, 7, 7, 8, 8, 8, 9, 9, 9]]))

In [29]:
# get unique values with np.repeat()
a = np.array([[1,2,1], [2,1,3], [4,5,1]])
rep = np.unique(a)

display(a), display(rep)

array([[1, 2, 1],
       [2, 1, 3],
       [4, 5, 1]])

array([1, 2, 3, 4, 5])

(None, None)

In [30]:
# TODO: this is weird

col_wise = np.unique(a, axis=0)
row_wise = np.unique(a, axis=1)
display(col_wise, row_wise)

array([[1, 2, 1],
       [2, 1, 3],
       [4, 5, 1]])

array([[1, 1, 2],
       [2, 3, 1],
       [4, 1, 5]])

In [31]:
# get diagonal values
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
diag = np.diagonal(a)
offset_1 = np.diagonal(a, offset=1)
offset_2 = np.diagonal(a, offset=-1)

a, diag, offset_1, offset_2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 5, 9]),
 array([2, 6]),
 array([4, 8]))

### Conversion

In [32]:
# conversion and storage
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

type(a), type(a.tolist()) # use tolist() to store in python list

(numpy.ndarray, list)

In [33]:
a = np.array([[10,20,30], [40,50,60], [70,80,90]])
display(a)
a.tofile("my_arr.txt", sep="\n")  # convert to a txt file

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Transposition

In [34]:
# transposition
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b, c = a.copy(), a.copy()

swapped = np.swapaxes(a, 0, 1)  # swaps axes 0 (rows) and 1 (columns)
transposed = b.transpose(1, 0)  # transposes the array (equivalent to swapping rows and columns)
short_transposed = c.T  # Another shorthand for transposition (equivalent to transpose())

a, swapped, transposed, short_transposed

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [35]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# a.shape = (2, 2, 2)

transposed_012 = np.transpose(a, (0, 1, 2))  # no change
transposed_021 = np.transpose(a, (0, 2, 1))  # swap last two axes
transposed_102 = np.transpose(a, (1, 0, 2))  # swap first two axes
transposed_210 = np.transpose(a, (2, 1, 0))  # reverse all axes

display(transposed_012)  # unchanged
display(transposed_021)  # different reshuffle
display(transposed_102)  # reshuffled again
display(transposed_210)  # completely reversed

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

### Operations on 2 matrices

In [36]:
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
add_ops = a + b
complex_ops = (a + b - 2 * a) / 4

a, b, add_ops, complex_ops

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]),
 array([[-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75]]))

#### Modulo

In [37]:
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

a_mod_b = a % b
b_mod_a = b % a

a,b, a_mod_b, b_mod_a

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0., 0., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.]]))

#### Floor Division

In [38]:
# using floor division operator. output is in int
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

floor_1 = a // b # this returns ints
floor_2 = b // a # this returns ints

a,b, floor_1, floor_2

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 1.],
        [2., 2., 3.],
        [3., 4., 4.]]))

In [39]:
# using np.floor() function. output is in float
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

floor_1 = np.floor(a/b) # this returns floats
floor_2 = np.floor(b/a) # this returns floats

a,b, floor_1, floor_2

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 1.],
        [2., 2., 3.],
        [3., 4., 4.]]))

#### Matrix Multiplication

In [40]:
# using element wise multiplication: a * b
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

prod = a * b

prod

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [41]:
# using matrix-wise multiplication: np.matmul(a, b) or a.dot(b) or by using @ operator
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

prod = np.matmul(a, b)
dot = a.dot(b)          # same effect as np.matmul(a, b)
at_operator = a @ b     # same effect as np.matmul(a, b)

prod, dot, at_operator

(array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]),
 array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]),
 array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]))