# NB Seup

In [1]:
import numpy as np

# Basics

## Arrays

In [2]:
a = np.arange(2, 10, 2) # start = 2, end = 10, step = 2
a, type(a), type(a[0])

(array([2, 4, 6, 8]), numpy.ndarray, numpy.int64)

In [3]:
# generate array from list
from_list = np.array([1,2,3])
from_list

array([1, 2, 3])

In [4]:
# assign data type on instantiation
a = np.array([1,2,3], dtype=np.int8)
a, type(a[0])

(array([1, 2, 3], dtype=int8), numpy.int8)

In [5]:
# 2D arrays
a = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [6]:
# 2D array using np.arange
a = np.array((np.arange(0,8,2), np.arange(1,8,2)), dtype=np.int8)
a

array([[0, 2, 4, 6],
       [1, 3, 5, 7]], dtype=int8)

In [7]:
# shapes 1D
a = np.array(np.arange(10), dtype=np.int8)
a, a.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8), (10,))

In [8]:
# shapes nD
a = np.array((np.arange(0, 10, 2), np.arange(0, 10, 2), np.arange(0, 10, 2)), dtype=np.int8)
a, a.shape

(array([[0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8]], dtype=int8),
 (3, 5))

In [9]:
a = a.reshape(1,15)
a, a.shape

(array([[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8]], dtype=int8), (1, 15))

In [10]:
a = a.reshape(5, 3)
a, a.shape

(array([[0, 2, 4],
        [6, 8, 0],
        [2, 4, 6],
        [8, 0, 2],
        [4, 6, 8]], dtype=int8),
 (5, 3))

In [11]:
# empty arrays
e = np.zeros((2,2))
e

array([[0., 0.],
       [0., 0.]])

In [12]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [13]:
# return random values (it returns unexpected results. use np.zeros instead)
a = np.empty((2,2))
b = np.empty((2,2,2))

a, b

(array([[0., 0.],
        [0., 0.]]),
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]))

In [14]:
# filled with 0, while main diagonal is filled with 1
a = np.eye(3)

# filled with 0, and fill 1 based on k parameter
b = np.eye(3, k=1)
c = np.eye(5, k=-2)

a,b,c

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]]))

In [15]:
a = np.eye(3)
a1 = a.copy()
a1[a1==0] = 2 # change all 0 values of the array to 2

b = a.copy()
b[b < 1] = 9

c = a.copy()
c[0] = 3 # change the first row of the array to 3
c[1] = 4 # change the second row of the array to 4

d = a.copy()
d[:, 0] = 5 # change the first column of the array to 5
d[:, -1] = 6 # change the last row of the array to 6

e = np.eye(5)
e[1:, :2] = -5 # change from the first row till the last row, and for the first 2 columns

a,b,c,d,e

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 9., 9.],
        [9., 1., 9.],
        [9., 9., 1.]]),
 array([[3., 3., 3.],
        [4., 4., 4.],
        [0., 0., 1.]]),
 array([[5., 0., 6.],
        [5., 1., 6.],
        [5., 0., 6.]]),
 array([[ 1.,  0.,  0.,  0.,  0.],
        [-5., -5.,  0.,  0.,  0.],
        [-5., -5.,  1.,  0.,  0.],
        [-5., -5.,  0.,  1.,  0.],
        [-5., -5.,  0.,  0.,  1.]]))

In [16]:
# sort arrays

a = np.eye(3)

a[1:, :2] = 4
a[0, 0] = 2
a[0, 1] = 9
a[0, -1] = 2
a[1:, -1] = 3

col_sort = np.sort(a, axis=0, kind='quicksort') # sort based on columns. quicksort is the default algo
row_sort = np.sort(a, axis=1, kind='quicksort') # sort based on rows, which is default (1). quicksort is the default algo
a, col_sort, row_sort


(array([[2., 9., 2.],
        [4., 4., 3.],
        [4., 4., 3.]]),
 array([[2., 4., 2.],
        [4., 4., 3.],
        [4., 9., 3.]]),
 array([[2., 2., 9.],
        [3., 4., 4.],
        [3., 4., 4.]]))

In [17]:
# copy arrays
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
my_view = a.view() # acts as python shallow copy()
my_copy = a.copy() # acts as python deepcopy()

# view() creates a new array object that shares the same data as a.
#   Modifying my_view will affect a, and vice versa (as long as the modifications are done at the element level).
#   However, if you change the structure (like reshaping my_view), it does not affect a.

# copy() creates a new independent array with the same values as a.
#   Modifying my_copy will NOT affect a, and vice versa.
#   This is equivalent to Python's deepcopy() in that it creates a fully independent copy.

my_view, my_copy

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

## Operations

### Fill an array

In [18]:
# fill an array
a = np.zeros((3,3), dtype=np.int64)
b = a.copy()

a[:] = 2  # Uses broadcasting
b.fill(8) # Uses optimized in-place filling (more faster than [:], because it does not create an intermediate object—it simply updates memory locations )
a, b

(array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]),
 array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]))

In [19]:
a = np.zeros((3,3), dtype=np.int64)
a.fill(8)
b = a.copy()

a -= 2 # using broadcasting
b += [1,2,3] # using broadcasting

a,b

(array([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]),
 array([[ 9, 10, 11],
        [ 9, 10, 11],
        [ 9, 10, 11]]))

In [20]:
a = np.zeros((3,3), dtype=np.float64)
a.fill(8)
b,c = a.copy(), a.copy()

b /= 3 # using broadcasting to divide all by 3
c /= [1, 2, 3] # using broadcasting to divide every row based on index

a,b,c

(array([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]]),
 array([[2.66666667, 2.66666667, 2.66666667],
        [2.66666667, 2.66666667, 2.66666667],
        [2.66666667, 2.66666667, 2.66666667]]),
 array([[8.        , 4.        , 2.66666667],
        [8.        , 4.        , 2.66666667],
        [8.        , 4.        , 2.66666667]]))

### Sum

In [21]:
# sum of arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]])

sum_all_vals = a.sum()      # sum of all elements
sum_col_wise = a.sum(axis=0)     # sum all elements from each column of the same row (col-wise)
sum_row_wise = a.sum(axis=1)    # sum all elements from each row of the same column (row-wise)

a, sum_all_vals, sum_col_wise, sum_row_wise


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.int64(45),
 array([12, 15, 18]),
 array([ 6, 15, 24]))

### Product

In [22]:
# prod of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

prod_all_vals = a.prod()
prod_col_wise = a.prod(axis=0)
prod_row_wise = a.prod(axis=1)

a, prod_all_vals, prod_col_wise, prod_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.int64(362880),
 array([ 28,  80, 162]),
 array([  6, 120, 504]))

### Mean

In [23]:
# mean (average) of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

mean_all_vals = a.mean()
mean_col_wise = a.mean(axis=0)
mean_row_wise = a.mean(axis=1)

a, mean_all_vals, mean_col_wise, mean_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.float64(5.0),
 array([4., 5., 6.]),
 array([2., 5., 8.]))

### Min - Max

In [24]:
# min max of arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

min_val = a.min()
max_val = a.max()
min_col_wise = a.min(0)
min_row_wise = a.min(1)

a, min_val, max_val, min_col_wise, min_row_wise

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.int64(1),
 np.int64(9),
 array([1, 2, 3]),
 array([1, 4, 7]))

In [25]:
# min max index of arrays

a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int64)

min_index = a.argmin()
max_index = a.argmax()

a, min_index, max_index

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 np.int64(0),
 np.int64(8))

### Peak to Peak

In [26]:
# peak-to-peak method

a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int64)
ptp = np.ptp(a)  # this equals to a.max() - a.min()
ptp

np.int64(8)

### Flatten

In [27]:
# flatten an array

a = np.array([[[0,1,2],[3,4,5], [6,7,8]], [[9,10,11],[12,13,14], [15,16,17]]])

# using reshape:
#   returns a new array with the same data but reshaped into a 1D array
#   may return a view or a copy, depending on the memory layout
#   less explicit than .ravel() or .flatten()
flatten_1 = a.reshape(a.size)
flatten_2 = a.reshape(-1)

# using flatten():
#   always returns a copy of the original array
#   changes to the new array do not affect the original array
#   takes an optional order argument ('C' for row-major, 'F' for column-major)
flat_method = a.flatten()

# using ravel():
#   returns a view of the array whenever possible (i.e., if the array is contiguous in memory)
#   if a view is returned, changes to ravel_method will affect the original array
#   if a copy is needed (e.g., if the array is not contiguous), it returns a new array
ravel_method = a.ravel()


a, flatten_1, flatten_2, flat_method, ravel_method

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]))

### Repeat

In [28]:
# repeat values/arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.repeat(255, 3) # first arg represents the value, the second arg represents the number of repetitions
repeat_arr_flat = np.repeat(a, 3)
repeat_arr_cols = np.repeat(a, 3, axis=0) # repeat col wise
repeat_arr_rows = np.repeat(a, 3, axis=1) # repeat row wise

a, b, repeat_arr_flat, repeat_arr_cols, repeat_arr_rows

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([255, 255, 255]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
        8, 8, 9, 9, 9]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]]),
 array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
        [4, 4, 4, 5, 5, 5, 6, 6, 6],
        [7, 7, 7, 8, 8, 8, 9, 9, 9]]))

In [29]:
# get unique values with np.repeat()
a = np.array([[1,2,1], [2,1,3], [4,5,1]])
rep = np.unique(a)

display(a), display(rep)

array([[1, 2, 1],
       [2, 1, 3],
       [4, 5, 1]])

array([1, 2, 3, 4, 5])

(None, None)

In [30]:
# TODO: this is weird

col_wise = np.unique(a, axis=0)
row_wise = np.unique(a, axis=1)
display(col_wise, row_wise)

array([[1, 2, 1],
       [2, 1, 3],
       [4, 5, 1]])

array([[1, 1, 2],
       [2, 3, 1],
       [4, 1, 5]])

In [31]:
# get diagonal values
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
diag = np.diagonal(a)
offset_1 = np.diagonal(a, offset=1)
offset_2 = np.diagonal(a, offset=-1)

a, diag, offset_1, offset_2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 5, 9]),
 array([2, 6]),
 array([4, 8]))

### Random




#### Non-distribution related

<table>
    <thead>
    <tr>
        <th><strong>Function</strong></th>
        <th><strong>Purpose</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><strong>rand()</strong></td>
        <td>Uniform random numbers between 0 and 1</td>
    </tr>
    <tr>
        <td><strong>random()</strong></td>
        <td>Uniform random numbers between 0 and 1</td>
    </tr>
    <tr>
        <td><strong>randint()</strong></td>
        <td>Random integers in a given range</td>
    </tr>
    <tr>
        <td><strong>choice()</strong></td>
        <td>Random selection from an array with or without replacement</td>
    </tr>
    <tr>
        <td><strong>shuffle()</strong></td>
        <td>In-place shuffling of an array</td>
    </tr>
    <tr>
        <td><strong>permutation()</strong></td>
        <td>Random permutation of array elements</td>
    </tr>
    <tr>
        <td><strong>seed()</strong></td>
        <td>Set the seed for reproducibility in random number generation</td>
    </tr>
    </tbody>
</table>

##### **rand()**

* Generates random numbers uniformly distributed between 0 and 1
    * Every number in the range [0,1] has an equal probability of being chose
    * This function is from the legacy random module (np.random.rand).
    * Takes ***n*** positional arguments, which represent the dimensions of the array
* Use cases:
    * ***Simulating probabilities***
    * ***random sampling***
    * ***noise generation***

In [32]:
# generate a single random float
print(np.random.rand())

# generate a 1D array with 5 random floats
display(np.random.rand(5))

# generate a 3x3 matrix of random floats
display(np.random.rand(3, 3))

# Generate a 2x3x4 array (3D)
display(np.random.rand(2, 3, 4))

0.10791686981888848


array([0.14267186, 0.90138914, 0.72951738, 0.06854506, 0.99570143])

array([[0.06493185, 0.92538898, 0.81903593],
       [0.93701496, 0.84552988, 0.71198397],
       [0.20077441, 0.67578177, 0.57415863]])

array([[[0.71804752, 0.50690759, 0.461481  , 0.10479769],
        [0.57030291, 0.88388083, 0.45194329, 0.43413962],
        [0.65089545, 0.74003914, 0.85100737, 0.8857229 ]],

       [[0.57747595, 0.34059934, 0.07011172, 0.19491781],
        [0.2363846 , 0.98805756, 0.55898116, 0.83535444],
        [0.02751919, 0.0638972 , 0.29190406, 0.61251628]]])

##### **random()**

* Similar to rand(), but returns numbers in the range [0, 1]
* This function is from the modern `np.random` API
* Takes 1 positional argument:
    * a tuple containing the dimensions size
* Use cases:
    * ***Normalizing random sampling***
    * ***General number generation***

In [33]:
# generate a single random float
print(np.random.random())

# generate a 1D array of 5 random numbers
display(np.random.random((5,)))

# generate a 3x3 matrix of random numbers
display(np.random.random((3, 3)))

# Generate a 2x3x4 array (3D)
display(np.random.random((2, 3, 4)))

0.5993883792242239


array([0.09312132, 0.9528228 , 0.87050569, 0.60439135, 0.0672045 ])

array([[0.19073918, 0.15385717, 0.1386757 ],
       [0.85380816, 0.77183428, 0.87865105],
       [0.89075135, 0.9826437 , 0.37294934]])

array([[[0.74512623, 0.15688801, 0.4462824 , 0.45923978],
        [0.48561419, 0.23926289, 0.21339979, 0.42809165],
        [0.7992289 , 0.94650484, 0.87973925, 0.15652826]],

       [[0.42236784, 0.74139197, 0.89185684, 0.49326144],
        [0.48750776, 0.25262204, 0.36127442, 0.29957946],
        [0.29122563, 0.72724154, 0.61724096, 0.11693898]]])

##### **randint()**

Generates random ints between `low` (inclusive) and `high` (exclusive)

* Takes 4 arguments:
    * `low` = start point
    * `height` = end point
    * `size` = size of the array
    * `dtype` = data type of the array (defaults to innt64)

* Use cases:
    * ***Simulating dice rolls***
    * ***Random selection***
    * ***Random Indexing***

In [34]:
# generate a single random ints between 10 and 50
display(np.random.randint(low=10, high=50))

# generate a 1D array of 5 random ints between 0 and 100
display(np.random.randint(low=0, high=100, size=5))

# generate a 3x3 matrix of random ints between 1 and 10 of type int8
display(np.random.randint(low=1, high=10, size=(3, 3), dtype = np.int8))

45

array([78, 79, 36,  5, 99], dtype=int32)

array([[1, 6, 5],
       [1, 4, 5],
       [9, 6, 5]], dtype=int8)

##### **choice()**

* Picks random elements from an array
* Can assign probabilities `p` to elements
* Use cases:
    * ***Random selection from a dataset***

In [35]:
# randomly select one element from the list
print(np.random.choice(a=[10, 20, 30, 40, 50]))

# generate an array of 10 random choices (with replacement)
display(np.random.choice(a=[10, 20, 30, 40, 50], size=10))

# generate an array of 5 unique choices (without replacement)
display(np.random.choice(a=[10, 20, 30, 40, 50], size=5, replace=False))  # this will generate all the numbers of a, but in a different order

10


array([20, 10, 20, 50, 20, 10, 50, 10, 20, 30])

array([50, 20, 10, 30, 40])

In [36]:
# example with probabilities using 'p' parameter
elements = [10, 20, 30, 40, 50]

# probabilities assigned to each element. sum of list must be equal to 1
probabilities = [0.1, 0.2, 0.4, 0.2, 0.1]

# randomly select one element with given probabilities
print(np.random.choice(a=elements, p=probabilities))

# generate an array of 10 random choices (with replacement)
display(np.random.choice(a=elements, size=10, p=probabilities))

# generate an array of 5 unique choices (without replacement)
#  if "replace" is False, "p" is ignored because each element can only be selected once.
display(np.random.choice(a=elements, size=5, replace=False))

10


array([10, 30, 40, 10, 40, 10, 30, 30, 50, 30])

array([30, 50, 20, 10, 40])

##### **shuffle()**

Shuffles an array in place (modifies the original array). It doesn't return a value
* Takes 1 argument:
    * `x` = the array to perform on
* Use Cases:
    * ***Shuffling data inplace form random experiments***
    * ***Shuffling cards***



In [37]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Original array before shuffle: {arr}")

np.random.shuffle(x=arr)

print(f"Original array after shuffle: {arr}")


Original array before shuffle: [1 2 3 4 5]
Original array after shuffle: [3 4 2 1 5]


##### **permutation()**

Randomly permutes (shuffles) the sequence of elements in an array. Returns a new array
* Takes 1 argument:
    * `x` = the array to perform on
* Use Cases:
    * ***Shuffling elements***
    * ***Randomizing order for experiments***


In [38]:
arr = np.array([1, 2, 3, 4, 5])

# return 5 copies of the array with items shuffled
for i in range(5):
    display(np.random.permutation(x=arr))

array([1, 5, 2, 3, 4])

array([4, 3, 2, 5, 1])

array([4, 3, 1, 5, 2])

array([1, 5, 4, 2, 3])

array([1, 5, 2, 3, 4])

##### **seed()**

* Sets the seed for the random number generator to ensure reproducibility
* The same seed will always generate the same sequence of random numbers
* Use Cases:
    * ***Ensure that the random numbers generated in experiments are reproducible for debugging or testing***

In [39]:
# set seed for the whole cell run. Note that this remains applied for the following cells
np.random.seed(42)

# generate 5 arrays with 3 random floats in it
#  rerunning this cell will cause the exact same results as before
for i in range(5):
    display(np.random.rand(3))

# reset to numpy default seed system, to prevent following notebooks get affected
np.random.seed(None)

array([0.37454012, 0.95071431, 0.73199394])

array([0.59865848, 0.15601864, 0.15599452])

array([0.05808361, 0.86617615, 0.60111501])

array([0.70807258, 0.02058449, 0.96990985])

array([0.83244264, 0.21233911, 0.18182497])

#### **Distribution based**

<table>
    <thead>
    <tr>
        <th><strong>Function</strong></th>
        <th><strong>Purpose</strong></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><strong>uniform()</strong></td>
        <td>Random numbers from a uniform distribution over a given range</td>
    </tr>
    <tr>
        <td><strong>binomial()</strong></td>
        <td>Number of successes in a fixed number of Bernoulli trialss</td>
    </tr>
    <tr>
        <td><strong>negative_binomial()</strong></td>
        <td>Number of failures before a fixed number of successes in Bernoulli trials</td>
    </tr>
    <tr>
        <td><strong>multinomial()</strong></td>
        <td>Random samples from a Multinomial distribution, which is a generalization of the binomial distribution</td>
    </tr>
    <tr>
        <td><strong>poisson()</strong></td>
        <td>Random samples from a Poisson distribution, modeling the number of events in a fixed interval</td>
    </tr>
    <tr>
        <td><strong>normal()</strong></td>
        <td>Random numbers from a normal distribution with a given mean and standard deviation</td>
    </tr>
    <tr>
        <td><strong>standard_normal()</strong></td>
        <td>Random numbers from the standard normal distribution (mean = 0, std = 1)</td>
    </tr>
    <tr>
        <td><strong>randn()</strong></td>
        <td>Random numbers from the standard normal distribution (mean = 0, std = 1)</td>
    </tr>
    <tr>
        <td><strong>standard_t()</strong></td>
        <td>Random samples from a Student’s t-distribution, used for small-sample hypothesis testing</td>
    </tr>
    <tr>
        <td><strong>exponential()</strong></td>
        <td>Random samples from an Exponential distribution, modeling time until an event occurs</td>
    </tr>
    <tr>
        <td><strong>beta()</strong></td>
        <td>Random samples from a Beta distribution, often used for probabilities and Bayesian statistics</td>
    </tr>
    <tr>
        <td><strong>gamma()</strong></td>
        <td>Random samples from a Gamma distribution, modeling waiting times and sum of exponentials</td>
    </tr>
    <tr>
        <td><strong>chisquare()</strong></td>
        <td>Random samples from a Chi-square distribution, used in hypothesis testing</td>
    </tr>
    <tr>
        <td><strong>geometric()</strong></td>
        <td>Number of trials until the first success in Bernoulli trials</td>
    </tr>
    <tr>
        <td><strong>hypergeometric()</strong></td>
        <td>Number of successes in a draw without replacement from a finite population</td>
    </tr>
    <tr>
        <td><strong>laplace()</strong></td>
        <td>	Random samples from a Laplace distribution (double exponential), used in signal processing</td>
    </tr>
    <tr>
        <td><strong>logistic()</strong></td>
        <td>Random samples from a Logistic distribution, used for modeling growth curves.</td>
    </tr>
    <tr>
        <td><strong>lognormal()</strong></td>
        <td>Random samples from a Log-normal distribution, where the log of the variable is normally distributed</td>
    </tr>
    <tr>
        <td><strong>rayleigh()</strong></td>
        <td>Random samples from a Rayleigh distribution, used in signal processing and wave modeling</td>
    </tr>
    <tr>
        <td><strong>triangular()</strong></td>
        <td>Random samples from a Triangular distribution, a simple distribution defined by min, mode, and max</td>
    </tr>
    <tr>
        <td><strong>vonmises()</strong></td>
        <td>Random samples from a Von Mises distribution, used for circular data (e.g., wind directions)</td>
    </tr>
    <tr>
        <td><strong>wald()</strong></td>
        <td>Random samples from a Wald (Inverse Gaussian) distribution, used in survival analysis</td>
    </tr>
    <tr>
        <td><strong>weibull()</strong></td>
        <td>Random samples from a Weibull distribution, commonly used in reliability analysis and failure modeling</td>
    </tr>
    </tbody>
</table>


##### **uniform()**

Generates a ***uniform ditribution***

Takes 3 arguments:
* `low` = min number. defaults to ***0.0***
* `high` = max number. defaults to ***1.0***
* `size` = the size of the array. defaults to None

Use cases:
* ***Random float generation with a fixed range***

In [40]:
# generate a single float between 5 and 10
print(np.random.uniform(low=5, high=10))

# generate an array of 5 floats between 20 and 50
display(np.random.uniform(low=20, high=50, size=5))

# generate a 3x3 matrix
display(np.random.uniform(low=1, high=100, size=(3, 3)))

5.46616695483154


array([32.3359572 , 47.41497605, 37.89929463, 27.28022706, 47.5018183 ])

array([[31.47921797, 40.65904183,  3.65309555],
       [17.65635886, 97.73650328, 73.12582224],
       [43.79477696, 93.63336735, 29.26796493]])

##### **binomial()**

* Models the number of successes in `n` trials with success probability `p`, where each trial has:
    * ***Probability of success*** = `p`
    * ***Probability of failure*** = `1 - p`

*  Use cases:
    * ***Coin flips***
    * ***Quality control***
    * ***Decision-making models***

In [41]:
# simulate flipping a coin 10 times, where success (heads) has probability 0.5
print(np.random.binomial(n=10, p=0.5))

# generate an array of 5 experiments
print(np.random.binomial(n=10, p=0.5, size=5))

5
[2 6 5 6 2]


##### **negative_binomial()**

* Generates random values from the ***negative binomial distribution***
* This distribution models the number of trials required to achieve a fixed number of successes in a sequence of independent trial
* Takes 3 arguments:
    * `n` = the number of successes
    * `p` = the probability of success on each trial
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling the trials needed for success***, such as:
        * ***Failure tests***
        * ***Performance evaluations***


In [42]:
 # generate 5 random values from a negative binomial distribution
display(np.random.negative_binomial(n=10, p=0.5, size=5))

array([8, 9, 7, 8, 7], dtype=int32)

##### **multinomial()**

* Generates random values from the multinomial distribution, which ***generalizes the binomial distribution*** for more than two outcomes
* It models the counts of various categories in a series of trials
* Takes 3 arguments:
    * `n` = the number of trials
    * `pvals` = an array of probabilities for each outcome
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling categorical outcomes***, such as:
        * ***Survey responses***
        * ***Gene sequencing***

In [43]:
# generates 5 samples from a multinomial distribution
display(np.random.multinomial(n=10, pvals=[0.2, 0.5, 0.3], size=5))

array([[2, 6, 2],
       [2, 5, 3],
       [1, 5, 4],
       [4, 6, 0],
       [2, 6, 2]], dtype=int32)

##### **poisson()**
* Models the number of events in a fixed time interval
* Takes 2 arguments:
    * `lam` (λ) = expected number of events per interval
    * `size` = number of samples
* Use cases:
    * ***Call center calls per hour***
    * ***Event modeling***:
        * ***Customer arrivals***
        * ***Traffic accidents***

In [44]:
# generate a single number with lambda=5
print(np.random.poisson(lam=5))

# generate an array of 5 values
print(np.random.poisson(lam=5, size=5))

3
[ 9  2  4 10  9]


##### **normal()**

Generates random numbers from a ***normal distribution*** with a specified mean and standard deviation

Takes 3 arguments:
* `loc` = ***Mean (μ)***
* `scale` = ***Standard deviation (σ)***

Use cases:
* ***Statistics***
* ***Finance***
* ***Physics simulations***

In [45]:
# generate a single random number with mean=50 and std dev=10
print(np.random.normal(loc=50, scale=10))

# generate an array of 5 values
display(np.random.normal(loc=50, scale=10, size=5))

# generate a 2x2 matrix
display(np.random.normal(loc=50, scale=10, size=(2, 2)))

32.10636153360166


array([54.29055514, 45.69074321, 43.97027417, 52.37569664, 31.43863289])

array([[54.55654245, 50.31071336],
       [59.10094057, 53.86781511]])

##### **standard_t()**

* Generates random values from the ***Student's t-distribution***, used in hypothesis testing and when sample sizes are small
* Takes 2 arguments:
    * `df` = degrees of freedom, parameter that controls the distribution's shape
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling data with heavy tails***, such as:
       * ***Stock returns***
       * ***Small-sample statistical inference***

In [46]:
 # generate 5 random values from a Student's t-distribution
display(np.random.standard_t(df=10, size=5))

array([-0.22554814,  0.65915646,  1.33129018, -0.35351138, -2.03972944])

##### **standard_normal()**
* Generates random numbers from a ***standard normal distribution***, which has:
    * Mean = 0
    * Standard Deviation = 1
* This is a special case of the normal distribution with fixed parameters (mean = 0, standard deviation = 1)
* This generates the same result as ***randn()***
* Takes 1 argument:
    * `size` = the number of random values to generate
* Use cases:
    * ***Simulations or modeling where you need data that follows a standard normal distribution***, such as:
        * ***Physics - Particle Movement (Brownian Motion)***
        * ***Biology - Genetic Variability***


In [47]:
# generate 5 random numbers from a standard normal distribution
random_array = np.random.standard_normal(5)

##### **randn()**

* Generate random numbers from a ***standard normal distribution*** meaning that:
    * Mean (μ) = 0
    * Standard deviation (σ) = 1
    * Bell-shaped curve (Gaussian distribution)
* This returns the same result as ***standard_normal()***
* Takes `n` arguments, representing the dimensions
* Use Case: Modeling real-world data like:
    * ***heights***
    * ***test scores***
    * ***financial returns***

In [48]:
# generate a single random number
print(np.random.randn())  # no args means single float

# generate a 1D array of 5 values
display(np.random.randn(5))  # d0=5

# generate a 3x3 matrix
display(np.random.randn(3, 3))  # d0=3, d1=3

-0.034525568435950185


array([ 0.83550826, -0.52483509,  1.07063215,  0.59715358, -0.15199133])

array([[-0.59087447, -1.626032  ,  1.71446578],
       [ 1.10184429, -1.50340648, -0.50280243],
       [-0.5652582 ,  1.3150034 , -0.28791246]])

##### **exponential()**

* Generates random numbers from an ***exponential distribution***, which models the time between events in a Poisson process
* Takes 2 arguments:
    * `scale` = 1 / λ  (inverse of the event rate)
    * `size` = number of samples
* Use Cases:
    * ***Waiting times*** (example: time between earthquakes or customer arrivals)
* Use Cases:
    * ***Modeling waiting times***:
        * ***The time between customer arrivals***

In [49]:
# Generate a single number with scale=2.0
print(np.random.exponential(scale=2.0))

# Generate an array of 5 values
print(np.random.exponential(scale=2.0, size=5))

2.851472074510295
[1.19621118 0.4645452  0.77845906 2.08441252 1.15751395]


##### **beta()**

* Models probabilities (values bwetween `0` and `1`)
* Takes 3 arguments:
    * `a` (alpha) = the shape parameter for the ***distribution's first part***. Controls the "left" side (the lower values)
    * `b` (beta) = the shape parameter for the ***distribution's second part***. Controls the "right" side (the higher values)
    * `size` = number of samples
* The shape of the distribution changes depending on the values of `a` and `b`:
    * When a = b = 1, the Beta distribution is a uniform distribution between 0 and 1.
    * When a > b, the distribution is ***skewed toward 1*** (more values near 1)
    * When a < b, the distribution is ***skewed toward 0*** (more values near 0)
    * When a = b > 1, the distribution has ***a bell-shaped curve*** centered around `0.5`
* Use cases:
    * ***Modeling probabilities***
    * ***Bayesian statistics***
    * ***A/B Testing***

In [50]:
# generates 5 random Beta-distributed values
display(np.random.beta(a=2.0, b=5.0, size=5))

array([0.24731408, 0.15554331, 0.41183582, 0.161236  , 0.64666002])

##### **gamma()**

* A ***generalization of the exponential distribution***, used for waiting times
* gamma() models waiting times in a Posson process

* Use Cases:
    * ***Reliability Engineering***
    * ***Risk Analysis***
    * ***Queing Models***
        * ***Arrival times in queues***

In [51]:
# generate a single number with shape=2.0 and scale=2.0
print(np.random.gamma(shape=2.0, scale=2.0))

# generate an array of 5 values
display(np.random.gamma(shape=2.0, scale=2.0, size=5))

0.6645841422453882


array([12.71145031,  1.02553848,  0.61013128,  0.28296993,  2.24462802])

##### **chisquare()**

* Generates random values from the ***chi-squared distribution***
* Takes 2 arguments:
    * `df` = degrees of freedom; it's the shape parameter (sometimes denoted as `k`)
    * `size` = the number of values to generate
* Use cases:
    * ***Used in chi-squared tests***
    * ***To model variances***
    * *** Hypothesis testing***


In [52]:
# generate 5 random values from a chi-squared distribution
display(np.random.chisquare(df=2.0, size=5))

array([1.44581043, 0.16557502, 0.56955542, 3.57402449, 0.74743119])

##### **geometric()**
Generates random values from a ***geometric distribution***, which models the number of trials needed before the first success in a sequence of Bernoulli trials
* Takes 2 arguments:
    * `p` = the probability of cuccess on each trial
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling the number of trials until the first success***, such as:
        * ***Quality control processes***
        * ***Search problems***


In [53]:
# generate 5 random values from a Geometric distribution
display(np.random.geometric(p=0.5, size=5))

array([5, 1, 4, 3, 6], dtype=int32)

##### **hypergeometric()**

* Generates random values from the ***hypergeometric distribution***
* This distribution models the number of successes in a sample drawn without replacement ***from a finite population***
* Takes 4 arguments:
    * `ngood` = the number of good items in the population
    * `nbad` = the number of bad items in the poopulation
    * `nsample` = the size of the sample drawn
    * `size` = the number of random values to generate
* Use cases:
    * ***Sampling without replacement***, such as:
        * ***Quality testing***
        * ***Survey sampling***


In [54]:
# generate 3 samples from a Hypergeometric distribution
display(np.random.hypergeometric(ngood=10, nbad=20, nsample=5, size=3))

array([2, 2, 1], dtype=int32)

##### **laplace()**

* Generates random values from a ***Laplace distribution***, also known as the ***double exponential distribution***
* This distribution is used to model the difference between two independent exponential variables
* Takes 3 arguments:
    * `loc` = the location parameter (mean)
    * `scale` = the divergence of spread of the distribution
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling data with large deviations or noise***, such as:
        * ***Image Processing***
        * ***Finance for price changes***

In [55]:
# generate 5 random values from a Laplace distribution
display(np.random.laplace(loc=0.0, scale=1.0, size=5))

array([ 2.76460825,  0.22947267,  0.73042163, -0.86086913,  1.95199798])

##### **logistic()**

* Generates random values from the ***logistic distribution*** commonly used in logistic regression and binary classification
* Takes 3 arguments:
    * `loc`= the location parameter (mean)
    * `scale` = the scale parameter (analogous to the ***standard deviation***)
    * `size` = the number of random values to generate
* Use cases:
    * ***Logistic Regression (growith processes)***
    * ***Binary Classification (binary outcomes)***
    * ***Modeling growth processes or binary ourcomes with an "S-shaped" curve***, such as:
        * ***Population growth***

In [56]:
 # generate 5 random values from a Logistic distribution
display(np.random.logistic(loc=0.0, scale=1.0, size=5))

array([-0.41217784,  1.89907131, -1.26251348, -0.75291441, -1.35476949])

##### **lognormal()**

* Generates random values from the ***log-normal distribution***, which is often used to model stock prices, income, and other positively skewed data
* Takes 3 arguments:
    * `mean` = the mean of the underlying normal distribution
    * `signam` = the standard deviation of the underlying normal distribution
    * `size` = the number of random values to generate
* Use cases:
    * ***Used to model data with positive skewness***, such as:
        * ***Financial returns***
        * ***Lifespan of products***


In [57]:
 # generate 5 random values from a log-normal distribution
display(np.random.lognormal(mean=0.0, sigma=1.0, size=5))

array([2.33725428, 1.67963667, 0.10552148, 0.55882612, 3.00201336])

##### **rayleigh()**

* Generates random values from the Rayleigh distribution, commonly used to model wind speed and other continuous random variables with skewed distributions
* Takes 2 arguments:
    * `scale` = the scale parameter, sometimes denoted as σ
    * `size` = the number of random values to generate
* Use cases:
    * ***Model non-negative data***, such as:
        * ***Signal Processing***
        * ***Natural Sciences***

In [58]:
# 5 generate random values from a rayleigh distribution
display(np.random.rayleigh(scale=2.0, size=5))

array([3.00515226, 2.24109376, 0.71437161, 1.28852271, 1.09430464])

##### **traingular()**

*  Generates random values from the ***triangular distribution***, which is commonly used in simulations to represent uncertain variables
* Takes 4 arguments:
    * `left` = the lower bound of the distribution
    * `mode` = the peak or most likely value
    * `right` = the upper bound of the distribution
    * `size` = the number of random values to generate
* Use cases:
    * ***Simulation modeling***, such as:
       * ***Project Management***
       * ***Risk analysis***

In [59]:
# generate 5 random values from a triangular distribution
display(np.random.triangular(left=0, mode=5, right=10, size=5))

array([4.02683938, 3.28791099, 1.96547048, 4.32661324, 6.27406521])

##### **vonmises()**
* Generates random values from the ***von Mises distribution***, which is a probability distribution for circular data (angles)
* Takes 3 arguments:
    * `mu` = the location parameter (mean angle)
    * `kappa` = the concatenation parameter, which controls the spread
    * `size` = the number of random values to generate
* Use cases:
    * ***Modeling circular data***, such as:
        * ***Wind direction***
        * ***Time of day***

In [60]:
# generate 5 random values from a von mises distribution
display(np.random.vonmises(mu=0.0, kappa=1.0, size=5))

array([-1.01575814,  0.94380415, -0.37616565,  0.38553754, -0.04913357])

##### **wald()**

* Generates random values from the ***Wald distribution***, which is used for modeling processes where the waiting times or durations of events vary
* Takes 3 arguments:
    * `mean` = the mean of the distribution
    * `scale` = the scale parameter
    * `size` = the number of random values to generate
* Use cases:
    * ***Queuing models***
    * ***Lifespan modeling***

In [61]:
# generate 5 random values from a wald distribution
display(np.random.wald(mean=1.0, scale=1.0, size=5))

array([2.56688508, 0.35808218, 1.31317225, 0.74756311, 0.75435115])

##### **weibull()**
* Generates random values from the ***Weibull distribution***, which is used in reliability analysis and survival analysis
* Takes 2 arguments:
    * `a` = the shape parameter
    * `size` = the number of random values to generate
* Use cases:
    * ***Failure time analysis***, such as:
        * ***Modeling product lifetimes***


In [62]:
 # generate 5 random values from a Weibull distribution
display(np.random.weibull(a=2.0, size=5))

array([0.62464054, 0.54362929, 0.79274295, 0.69910217, 1.0478448 ])

### Conversion

In [63]:
# conversion and storage
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

type(a), type(a.tolist()) # use tolist() to store in python list

(numpy.ndarray, list)

In [64]:
a = np.array([[10,20,30], [40,50,60], [70,80,90]])
display(a)
a.tofile("my_arr.txt", sep="\n")  # convert to a txt file

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Transposition

In [65]:
# transposition
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b, c = a.copy(), a.copy()

swapped = np.swapaxes(a, 0, 1)  # swaps axes 0 (rows) and 1 (columns)
transposed = b.transpose(1, 0)  # transposes the array (equivalent to swapping rows and columns)
short_transposed = c.T  # Another shorthand for transposition (equivalent to transpose())

a, swapped, transposed, short_transposed

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [66]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# a.shape = (2, 2, 2)

transposed_012 = np.transpose(a, (0, 1, 2))  # no change
transposed_021 = np.transpose(a, (0, 2, 1))  # swap last two axes
transposed_102 = np.transpose(a, (1, 0, 2))  # swap first two axes
transposed_210 = np.transpose(a, (2, 1, 0))  # reverse all axes

display(transposed_012)  # unchanged
display(transposed_021)  # different reshuffle
display(transposed_102)  # reshuffled again
display(transposed_210)  # completely reversed

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

### Operations on 2 matrices

In [67]:
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
add_ops = a + b
complex_ops = (a + b - 2 * a) / 4

a, b, add_ops, complex_ops

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]),
 array([[-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75]]))

#### Modulo

In [68]:
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

a_mod_b = a % b
b_mod_a = b % a

a,b, a_mod_b, b_mod_a

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0., 0., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.]]))

#### Floor Division

In [69]:
# using floor division operator. output is in int
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

floor_1 = a // b # this returns ints
floor_2 = b // a # this returns ints

a,b, floor_1, floor_2

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 1.],
        [2., 2., 3.],
        [3., 4., 4.]]))

In [70]:
# using np.floor() function. output is in float
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

floor_1 = np.floor(a/b) # this returns floats
floor_2 = np.floor(b/a) # this returns floats

a,b, floor_1, floor_2

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 1.],
        [2., 2., 3.],
        [3., 4., 4.]]))

#### Matrix Multiplication

In [71]:
# using element wise multiplication: a * b
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

prod = a * b

prod

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [72]:
# using matrix-wise multiplication: np.matmul(a, b) or a.dot(b) or by using @ operator
a = np.zeros((3,3))
a.fill(2)
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

prod = np.matmul(a, b)
dot = a.dot(b)          # same effect as np.matmul(a, b)
at_operator = a @ b     # same effect as np.matmul(a, b)

prod, dot, at_operator

(array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]),
 array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]),
 array([[24., 30., 36.],
        [24., 30., 36.],
        [24., 30., 36.]]))